import { Product, Testimonial } from './types';

export const PRODUCTS: Product[] = [
  // ==================== CAKES (1 - 25) ====================
  {
    id: 'cake-1',
    name: 'Belgian Chocolate Truffle Cake',
    description: 'Layers of rich Belgian dark chocolate ganache and moist chocolate sponge, finished with hand-painted 24k gold leaf and premium chocolate curls.',
    price: 1250,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    tags: ['Bestseller', 'Eggless', 'Chef\'s Special', 'Must Try'],
    ingredients: ['Belgian Cocoa 70%', 'French Cream', 'Organic Wheat Flour', 'Bourbon Vanilla Bean'],
    nutritionalInfo: 'Calories: 380 kcal | Fat: 22g | Sugar: 28g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-2',
    name: 'Classic Black Forest Cake',
    description: 'A luxurious take on the classic: moist dark chocolate sponge layers infused with Kirsch cherry syrup, filled with premium dark cherries and rich whipped cream.',
    price: 950,
    category: 'Cakes',
    rating: 4.8,
    reviewsCount: 98,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    tags: ['Classic', 'Eggless', 'All-Time Favorite'],
    ingredients: ['Dark Cherries', 'Whipped Cream', 'Chocolate Flakes', 'Kirsch Infusion'],
    nutritionalInfo: 'Calories: 340 kcal | Fat: 18g | Sugar: 24g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-3',
    name: 'Royal Red Velvet Cake',
    description: 'Velvety crimson sponge layered with a decadent Madagascar vanilla cream cheese frosting, decorated with beautiful ruby-red velvet crumbs.',
    price: 1100,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 120,
    image: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=600&auto=format&fit=crop&q=80',
    tags: ['Signature', 'Eggless', 'Bestseller'],
    ingredients: ['Buttermilk', 'Premium Cream Cheese', 'Madagascar Vanilla', 'Cocoa Powder'],
    nutritionalInfo: 'Calories: 390 kcal | Fat: 24g | Sugar: 30g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-4',
    name: 'Gourmet Butterscotch Cake',
    description: 'Fluffy brown sugar sponge layered with premium butterscotch cream, crunchy homemade praline, and a rich, warm butterscotch drizzle.',
    price: 900,
    category: 'Cakes',
    rating: 4.7,
    reviewsCount: 84,
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c13636?w=600&auto=format&fit=crop&q=80',
    tags: ['Crunchy', 'Eggless', 'Caramel'],
    ingredients: ['Caramelised Praline', 'Brown Sugar Sponge', 'Butterscotch Fudge', 'Sweet Butter'],
    nutritionalInfo: 'Calories: 360 kcal | Fat: 16g | Sugar: 32g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-5',
    name: 'Imperial Pineapple Cake',
    description: 'A light and airy sponge soaked with sweet pineapple compote, decorated with premium glazed pineapple slices and delicious maraschino cherries.',
    price: 850,
    category: 'Cakes',
    rating: 4.6,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&auto=format&fit=crop&q=80',
    tags: ['Refreshing', 'Sugar-Free', 'Light'],
    ingredients: ['Pineapple Compote', 'Spun Sugar', 'Whipped Dairy Cream', 'Vanilla Sponge'],
    nutritionalInfo: 'Calories: 290 kcal | Fat: 12g | Sugar: 25g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-6',
    name: 'Strawberry Fields Cake',
    description: 'Elegant fresh summer strawberry purée layered with light white chocolate mousse and soft chiffon sponge, topped with fresh strawberries.',
    price: 1050,
    category: 'Cakes',
    rating: 4.8,
    reviewsCount: 105,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&auto=format&fit=crop&q=80',
    tags: ['Seasonal', 'Eggless', 'Fresh Fruit'],
    ingredients: ['Fresh Handpicked Strawberries', 'White Chocolate Mousse', 'Chiffon Sponge', 'Vanilla Ganache'],
    nutritionalInfo: 'Calories: 310 kcal | Fat: 15g | Sugar: 26g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-7',
    name: 'Blueberry Swirl Cheesecake',
    description: 'A baked New York style cheesecake with a thick graham cracker crust, topped with a luscious wild blueberry compote swirl.',
    price: 1350,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 156,
    image: 'https://images.unsplash.com/photo-1524351199679-46cddf530c04?w=600&auto=format&fit=crop&q=80',
    tags: ['Bestseller', 'Eggless', 'Artisanal'],
    ingredients: ['Philadelphia Cream Cheese', 'Wild Blueberries', 'Graham Cracker', 'Organic Lemon Zest'],
    nutritionalInfo: 'Calories: 410 kcal | Fat: 28g | Sugar: 22g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: false
  },
  {
    id: 'cake-8',
    name: 'Ferrero Rocher Roché Cake',
    description: 'A dream for chocolate lovers: rich hazelnut cake layered with dark chocolate Nutella frosting, toasted hazelnuts, and gold-foiled Ferrero Rochers.',
    price: 1450,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 168,
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=600&auto=format&fit=crop&q=80',
    tags: ['Exclusive', 'Eggless', 'Luxury Select'],
    ingredients: ['Ferrero Rocher', 'Toasted Hazelnuts', 'Nutella Ganache', 'Crisp Wafer Shards'],
    nutritionalInfo: 'Calories: 460 kcal | Fat: 31g | Sugar: 34g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-9',
    name: 'Belgian Cocoa Symphony Cake',
    description: 'For absolute chocolate purists. Multi-texture cake featuring rich flourless chocolate sponge, smooth chocolate cremeux, and glossy mirror glaze.',
    price: 1400,
    category: 'Cakes',
    rating: 5.0,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&auto=format&fit=crop&q=80',
    tags: ['Premium', 'Sugar-Free', 'Dark Chocolate'],
    ingredients: ['Flourless Sponge', '72% Belgian Chocolate', 'Gold Dusting', 'Cacao Nibs'],
    nutritionalInfo: 'Calories: 420 kcal | Fat: 29g | Sugar: 20g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-10',
    name: 'Celebration Rainbow Cake',
    description: 'Stunning layers of vibrant, fruit-flavored vanilla sponge mirroring the rainbow, covered in fluffy vanilla bean cream and golden sprinkles.',
    price: 1200,
    category: 'Cakes',
    rating: 4.7,
    reviewsCount: 54,
    image: 'https://images.unsplash.com/photo-1557925923-cd4648e21187?w=600&auto=format&fit=crop&q=80',
    tags: ['Festive', 'Kids Favorite'],
    ingredients: ['Vibrant Chiffon Layers', 'Swiss Meringue Buttercream', 'Aromatic Citrus Oils', 'Gold Sprinkles'],
    nutritionalInfo: 'Calories: 350 kcal | Fat: 16g | Sugar: 35g per 100g',
    sizes: ['1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-11',
    name: 'Premium Alphonso Mango Cake',
    description: 'Exquisite layered sponge with fresh Alphonso mango pulp, velvet vanilla cream, and topped with delicate white chocolate curls and mango glaze.',
    price: 1150,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 67,
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c13636?w=600&auto=format&fit=crop&q=80',
    tags: ['Seasonal', 'Signature'],
    ingredients: ['Alphonso Mangoes', 'Vanilla Sponge', 'Fresh Cream', 'Mango Puree'],
    nutritionalInfo: 'Calories: 280 kcal | Fat: 11g | Sugar: 24g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-12',
    name: 'Madagascar Vanilla Bean Cake',
    description: 'An elegant vanilla lover\'s dream made with genuine Madagascar bourbon vanilla bean caviar, rich white sponge, and custom piping.',
    price: 900,
    category: 'Cakes',
    rating: 4.7,
    reviewsCount: 43,
    image: 'https://images.unsplash.com/photo-1464349110296-4d54f789f6c4?w=600&auto=format&fit=crop&q=80',
    tags: ['Classic', 'Pure flavor'],
    ingredients: ['Bourbon Vanilla Bean', 'Organic Flour', 'Buttercream', 'Eggless Sponge Mix'],
    nutritionalInfo: 'Calories: 310 kcal | Fat: 14g | Sugar: 26g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-13',
    name: 'Swiss Hazelnut Praline Gateau',
    description: 'Viennese hazelnut biscuit filled with rich Swiss milk chocolate ganache and roasted hazelnut praline flakes, finished with gold dust.',
    price: 1399,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    tags: ['Luxury Select', 'Premium'],
    ingredients: ['Swiss Chocolate', 'Hazelnuts', 'Praline Paste', 'A2 Cream'],
    nutritionalInfo: 'Calories: 440 kcal | Fat: 27g | Sugar: 29g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-14',
    name: 'Pistachio Cardamom Fusion Cake',
    description: 'An fusion dessert bringing together finely ground Persian pistachios, warm aromatic cardamom, and velvety rose-water whipped cream.',
    price: 1250,
    category: 'Cakes',
    rating: 4.8,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&auto=format&fit=crop&q=80',
    tags: ['Fusion Special', 'Royalty Select'],
    ingredients: ['Persian Pistachios', 'Aromatic Cardamom', 'Rose Water', 'Organic Saffron sponge'],
    nutritionalInfo: 'Calories: 395 kcal | Fat: 21g | Sugar: 22g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-15',
    name: 'Salted Caramel Pecan Cheesecake',
    description: 'Rich, dense, baked New York cheesecake topped with deep amber sea-salted caramel drizzle and abundance of toasted pecan nuts.',
    price: 1400,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 74,
    image: 'https://images.unsplash.com/photo-1524351199679-46cddf530c04?w=600&auto=format&fit=crop&q=80',
    tags: ['Decadent', 'Best Seller'],
    ingredients: ['Philadelphia Cheese', 'Toasted Pecans', 'Sea Salt', 'Amish Cream Butter'],
    nutritionalInfo: 'Calories: 450 kcal | Fat: 31g | Sugar: 25g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: false
  },
  {
    id: 'cake-16',
    name: 'Tiramisu Classico Gateau',
    description: 'A delicate Italian classic made with coffee-soaked ladyfinger biscuits layered with a whipped mixture of egg yolks, sugar, and mascarpone cheese.',
    price: 1300,
    category: 'Cakes',
    rating: 5.0,
    reviewsCount: 96,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
    tags: ['Classic', 'Italian Specialty'],
    ingredients: ['Mascarpone', 'Espresso Extract', 'Cocoa Dusting', 'Savoiardi biscuits'],
    nutritionalInfo: 'Calories: 320 kcal | Fat: 19g | Sugar: 20g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: false
  },
  {
    id: 'cake-17',
    name: 'Lemon Blueberry Meringue Cake',
    description: 'Zesty lemon sponge layered with rich wild blueberry compote and topped with toasted sweet Italian meringue swirls.',
    price: 1099,
    category: 'Cakes',
    rating: 4.6,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop&q=80',
    tags: ['Zesty', 'Summer Vibe'],
    ingredients: ['Organic Lemons', 'Wild Blueberries', 'Italian Meringue', 'Buttermilk'],
    nutritionalInfo: 'Calories: 285 kcal | Fat: 10g | Sugar: 27g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-18',
    name: 'Dark Chocolate Raspberry Gateau',
    description: 'Deep 74% dark chocolate fudge cake layered with tart raspberry coulis and decorated with fresh red raspberries and chocolate shards.',
    price: 1350,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 61,
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&auto=format&fit=crop&q=80',
    tags: ['Gourmet', 'Dark & Rich'],
    ingredients: ['74% Cocoa', 'Wild Raspberries', 'Fudge Frosting', 'Almond extract'],
    nutritionalInfo: 'Calories: 410 kcal | Fat: 24g | Sugar: 22g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-19',
    name: 'Coconut Cream Raffaello Cake',
    description: 'Soft white sponge soaked in sweet coconut milk, layered with white chocolate ganache and roasted almonds, coated in shredded organic coconut flakes.',
    price: 1100,
    category: 'Cakes',
    rating: 4.8,
    reviewsCount: 49,
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&auto=format&fit=crop&q=80',
    tags: ['Exotic', 'All-White Theme'],
    ingredients: ['Organic Coconut', 'White Chocolate', 'Almond Pieces', 'Condensed Milk'],
    nutritionalInfo: 'Calories: 370 kcal | Fat: 20g | Sugar: 29g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-20',
    name: 'Espresso Arabica Fudge Cake',
    description: 'Robust dark chocolate cake infused with freshly pulled shots of premium Arabica espresso, frosted with rich coffee buttercream.',
    price: 1150,
    category: 'Cakes',
    rating: 4.7,
    reviewsCount: 57,
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=600&auto=format&fit=crop&q=80',
    tags: ['Coffee Lover', 'Rich'],
    ingredients: ['Arabica Espresso', 'Cocoa Solids', 'Dark Ganache', 'Amul Butter'],
    nutritionalInfo: 'Calories: 390 kcal | Fat: 21g | Sugar: 25g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-21',
    name: 'Exotic Tropical Fruit Gateau',
    description: 'A light chiffon cake filled with layers of vanilla custard and a fresh medley of kiwi, strawberries, dragon fruit, and peaches.',
    price: 1200,
    category: 'Cakes',
    rating: 4.8,
    reviewsCount: 71,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&auto=format&fit=crop&q=80',
    tags: ['Healthy Choice', 'Fresh Cut'],
    ingredients: ['Kiwi', 'Strawberries', 'Peaches', 'Chiffon Sponge', 'Vanilla Custard'],
    nutritionalInfo: 'Calories: 260 kcal | Fat: 9g | Sugar: 21g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-22',
    name: 'White Chocolate Rose Petal Cake',
    description: 'A romantic, fragrant fusion: velvet white chocolate mousse paired with real organic rose petal jam (Gulkand) and soft rosewater sponge.',
    price: 1250,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 39,
    image: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=600&auto=format&fit=crop&q=80',
    tags: ['Fragrant', 'Signature'],
    ingredients: ['Rose Petal Jam', 'White Chocolate Mousse', 'Rose Water Extract', 'Gold Flakes'],
    nutritionalInfo: 'Calories: 350 kcal | Fat: 16g | Sugar: 28g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-23',
    name: 'German Forest Honey & Nut Cake',
    description: 'Warm spiced honey biscuit layers separated by premium vanilla sour-cream frosting, topped with caramelized walnuts and forest honey glaze.',
    price: 1280,
    category: 'Cakes',
    rating: 4.8,
    reviewsCount: 33,
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c13636?w=600&auto=format&fit=crop&q=80',
    tags: ['Traditional', 'Warm & Nutty'],
    ingredients: ['Organic Forest Honey', 'Toasted Walnuts', 'Sour Cream Frosting', 'Cinnamon'],
    nutritionalInfo: 'Calories: 380 kcal | Fat: 18g | Sugar: 31g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-24',
    name: 'Matcha Green Tea Velvet Cake',
    description: 'Earthy and smooth cake layered with authentic Japanese Uji matcha infused cream cheese and soft vanilla sponge cake.',
    price: 1350,
    category: 'Cakes',
    rating: 4.7,
    reviewsCount: 28,
    image: 'https://images.unsplash.com/photo-1524351199679-46cddf530c04?w=600&auto=format&fit=crop&q=80',
    tags: ['Exotic', 'Less Sweet'],
    ingredients: ['Uji Matcha Powder', 'Cream Cheese', 'Chiffon Layer', 'White Cacao Butter'],
    nutritionalInfo: 'Calories: 330 kcal | Fat: 15g | Sugar: 18g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },
  {
    id: 'cake-25',
    name: 'Luxe Lavender Earl Grey Cake',
    description: 'Stunning French tea-infused cake sponge layered with hints of real lavender nectar and smooth bergamot orange buttercream frosting.',
    price: 1290,
    category: 'Cakes',
    rating: 4.9,
    reviewsCount: 41,
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop&q=80',
    tags: ['Gourmet', 'Floral scent'],
    ingredients: ['Earl Grey Tea leaves', 'Lavender Nectar', 'Bergamot Essence', 'Eggless Sponge'],
    nutritionalInfo: 'Calories: 310 kcal | Fat: 12g | Sugar: 22g per 100g',
    sizes: ['0.5 kg', '1.0 kg', '2.0 kg'],
    customizable: true
  },

  // ==================== SWEETS (26 - 55) ====================
  {
    id: 'sweet-1',
    name: 'Shahi Saffron Gulab Jamun',
    description: 'Soft, golden-brown dumplings made of rich khoya, fried in pure desi ghee and soaked in cardamom and Kashmiri saffron infused warm sugar syrup.',
    price: 350,
    category: 'Sweets',
    rating: 4.9,
    reviewsCount: 210,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Bestseller', 'Eggless', 'Hot Delight'],
    ingredients: ['Rich Milk Solids (Khoya)', 'Desi Ghee', 'Kashmiri Saffron', 'Cardamom Seeds'],
    nutritionalInfo: 'Calories: 320 kcal | Fat: 14g | Sugar: 28g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-2',
    name: 'Kashmiri Saffron Rasgulla',
    description: 'Spongy and feather-light chenna discs boiled in purified light sugar syrup, infused with delicate saffron and organic rose water extract.',
    price: 320,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 145,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=600&auto=format&fit=crop&q=80',
    tags: ['Soft & Spongy', 'Eggless', 'Bestseller', 'Low Fat Option'],
    ingredients: ['Fresh Cow Milk Chenna', 'Organic Sugar Syrup', 'Saffron Strands', 'Rose Water'],
    nutritionalInfo: 'Calories: 180 kcal | Fat: 4g | Sugar: 20g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-3',
    name: 'Gold Foil Kaju Katli',
    description: 'Ultra-thin, melt-in-mouth diamonds made of selected premium cashew nuts and pure organic sugar, finished with edible 24k silver/gold foil.',
    price: 450,
    category: 'Sweets',
    rating: 4.9,
    reviewsCount: 320,
    image: 'https://images.unsplash.com/photo-1605197584547-c93ef1a9c5be?w=600&auto=format&fit=crop&q=80',
    tags: ['Bestseller', 'Eggless', 'Royalty Select'],
    ingredients: ['Premium Cashews (Grade W180)', 'Desi Ghee', 'Purified Sugar', 'Edible Silver Vark'],
    nutritionalInfo: 'Calories: 450 kcal | Fat: 22g | Sugar: 32g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-4',
    name: 'Ghee Mysore Pak',
    description: 'A traditional southern royalty sweet made of premium roasted chickpea flour, slow-simmered with abundant pure A2 Desi Ghee till porous and rich.',
    price: 420,
    category: 'Sweets',
    rating: 4.9,
    reviewsCount: 185,
    image: 'https://images.unsplash.com/photo-1621941400262-6cfa733d7b87?w=600&auto=format&fit=crop&q=80',
    tags: ['Traditional Ghee', 'Eggless', 'Chef\'s Special'],
    ingredients: ['Pure Desi Ghee', 'Roasted Gram Flour', 'Finely Powdered Sugar', 'Cardamom Powder'],
    nutritionalInfo: 'Calories: 520 kcal | Fat: 34g | Sugar: 38g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-5',
    name: 'Crispy Saffron Jalebi',
    description: 'Crisp, spiral-shaped traditional funnel cakes fried to perfection, dipped in a premium warm saffron sugar syrup for that quintessential sweet crunch.',
    price: 300,
    category: 'Sweets',
    rating: 4.7,
    reviewsCount: 130,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    tags: ['Crispy Hot', 'Eggless', 'Bestseller', 'Classic Delight'],
    ingredients: ['Fermented Wheat Batter', 'Pure Ghee', 'Kashmiri Saffron syrup', 'Rose infusion'],
    nutritionalInfo: 'Calories: 380 kcal | Fat: 15g | Sugar: 45g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-6',
    name: 'Desi Ghee Motichoor Laddu',
    description: 'Tiny pearl-like chickpea flour globules fried in ghee, mixed with premium saffron, melon seeds, and cashew bits, shaped into absolute golden orbs of happiness.',
    price: 380,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 260,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Bestseller', 'Temple Special'],
    ingredients: ['Desi Ghee', 'Fine Gram Flour (Besan)', 'Melon Seeds', 'Saffron Extract', 'Pistachios'],
    nutritionalInfo: 'Calories: 410 kcal | Fat: 19g | Sugar: 33g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-7',
    name: 'Kesar Milk Peda',
    description: 'Mouthwatering condensed milk fudge delicately flavored with cardamom and Kashmiri saffron, shaped elegantly with a decorative almond core.',
    price: 360,
    category: 'Sweets',
    rating: 4.7,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    tags: ['Rich Milk', 'Kids Favorite'],
    ingredients: ['Reduced Organic Milk Solids', 'Organic Cane Sugar', 'Saffron Petals', 'Almond Slivers'],
    nutritionalInfo: 'Calories: 390 kcal | Fat: 17g | Sugar: 28g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-8',
    name: 'Crisp Flaky Soan Papdi',
    description: 'A light, flaky, and crisp sweet that melts in your mouth instantly. Elaborate multi-layered threads of roasted gram flour and premium dry fruits.',
    price: 330,
    category: 'Sweets',
    rating: 4.6,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=600&auto=format&fit=crop&q=80',
    tags: ['Flaky', 'Gift Classic'],
    ingredients: ['Roasted Gram Flour', 'Fine Wheat Flour', 'Pure Desi Ghee', 'Almond & Pistachio toppings'],
    nutritionalInfo: 'Calories: 430 kcal | Fat: 20g | Sugar: 35g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-9',
    name: 'Royal Dry Fruit Barfi',
    description: 'Sugar-free, ultra-healthy, chewy rectangular fudge bars made entirely from crushed dates, premium walnuts, pistachios, almonds, and cashew nuts.',
    price: 600,
    category: 'Sweets',
    rating: 4.9,
    reviewsCount: 115,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Sugar-Free', 'Eggless', 'Bestseller', 'Healthy Luxury'],
    ingredients: ['Premium Dates', 'Anjeer (Figs)', 'California Almonds', 'Salted Pistachios', 'Walnuts'],
    nutritionalInfo: 'Calories: 280 kcal | Fat: 12g | Sugar: 0g (Natural date sugars only)',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-10',
    name: 'Pure Badam Almond Halwa',
    description: 'Ultra-rich traditional Indian pudding made of pure almond paste slow-cooked with ghee, milk, and saffron till it reaches a dense golden perfection.',
    price: 580,
    category: 'Sweets',
    rating: 5.0,
    reviewsCount: 150,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Signature', 'Sugar-Free', 'Eggless', 'Royal Rich'],
    ingredients: ['Blanched California Almonds', 'Pure Cow Ghee', 'Organic Cardamom', 'Saffron extract'],
    nutritionalInfo: 'Calories: 490 kcal | Fat: 30g | Sugar: 24g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-11',
    name: 'Handcrafted Pistachio Pista Roll',
    description: 'Premium Iranian pistachio paste wrapped around soft, sweetened cashew paste layers, shaped into delicious green and white rolls.',
    price: 490,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1605197584547-c93ef1a9c5be?w=600&auto=format&fit=crop&q=80',
    tags: ['Pistachio', 'Eggless', 'Sugar-Free', 'Nutty'],
    ingredients: ['Premium Pistachios', 'Grade-W Cashews', 'Fine Sugar', 'Ghee Coat'],
    nutritionalInfo: 'Calories: 460 kcal | Fat: 24g | Sugar: 30g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-12',
    name: 'Shahi Malai Chum Chum',
    description: 'Classic oval-shaped Bengali sweet made of soft chenna, cooked in sugar syrup, slit, and filled with rich mawa and organic dry fruits.',
    price: 360,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 81,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Bengali Classic', 'Eggless', 'Bestseller', 'Creamy'],
    ingredients: ['Milk Chenna', 'Mawa filling', 'Sliced Pistachios', 'Rosewater essence'],
    nutritionalInfo: 'Calories: 290 kcal | Fat: 11g | Sugar: 26g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-13',
    name: 'Premium Kesar Rasmalai Cup',
    description: 'Ultra-soft cottage cheese patties soaked in thick, slow-simmered rabri milk flavored with Kashmiri saffron, cardamom, and sliced almonds.',
    price: 380,
    category: 'Sweets',
    rating: 5.0,
    reviewsCount: 290,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=600&auto=format&fit=crop&q=80',
    tags: ['All-Time Favorite', 'Eggless', 'Bestseller'],
    ingredients: ['Cottage Cheese', 'Concentrated Milk (Rabri)', 'Kashmiri Saffron', 'Pistachio slivers'],
    nutritionalInfo: 'Calories: 220 kcal | Fat: 8g | Sugar: 18g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-14',
    name: 'Golden Kesar Kalakand',
    description: 'A delicate, crumbly sweet cake prepared by reducing milk with sugar and saffron, topped with silver leaf and crunchy almonds.',
    price: 390,
    category: 'Sweets',
    rating: 4.7,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    tags: ['Crumbly', 'Pure Milk'],
    ingredients: ['Reduced Whole Milk', 'Saffron', 'Sugar', 'Silver Foil vark'],
    nutritionalInfo: 'Calories: 340 kcal | Fat: 15g | Sugar: 23g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-15',
    name: 'Dharwad Peda Premium',
    description: 'An authentic delicacy from Karnataka: browned milk solids kneaded with sugar, cardamoms, and rolled in fine sugar granules.',
    price: 340,
    category: 'Sweets',
    rating: 4.9,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Heritage Recipe', 'Rich Taste'],
    ingredients: ['Browned Khoya', 'Cardamom', 'Ghee', 'Fine sugar coating'],
    nutritionalInfo: 'Calories: 410 kcal | Fat: 16g | Sugar: 29g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-16',
    name: 'Premium Mango Malai Peda',
    description: 'Rich condensed milk fudge blended with real Alphonso mango pulp and premium mawa, featuring an elegant cashew core.',
    price: 380,
    category: 'Sweets',
    rating: 4.7,
    reviewsCount: 63,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    tags: ['Fruit flavor', 'Summer Favorite'],
    ingredients: ['Alphonso Mango Pulp', 'Khoya Solids', 'Ghee', 'Cardamom'],
    nutritionalInfo: 'Calories: 370 kcal | Fat: 14g | Sugar: 26g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-17',
    name: 'Shahi Khoya Kadam',
    description: 'A sweet inside a sweet: spongy mini rasgulla encapsulated in soft, melt-in-the-mouth khoya fudge, dusted with grated dry coconut.',
    price: 400,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 51,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Complex Sweet', 'Double Joy'],
    ingredients: ['Chenna Rasgulla', 'Premium Khoya Outer', 'Grated Coconut', 'Cardamom Powder'],
    nutritionalInfo: 'Calories: 330 kcal | Fat: 12g | Sugar: 31g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-18',
    name: 'Pure Desi Ghee Besan Laddu',
    description: 'Golden round balls made of slow-roasted coarse chickpea flour (besan) in abundant A2 cow ghee, flavored with roasted nuts and cardamom.',
    price: 350,
    category: 'Sweets',
    rating: 4.9,
    reviewsCount: 154,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Homestyle', 'Traditional'],
    ingredients: ['Roasted Coarse Besan', 'A2 Desi Ghee', 'Raw Sugar (Bura)', 'Almonds & Pistachios'],
    nutritionalInfo: 'Calories: 480 kcal | Fat: 28g | Sugar: 24g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-19',
    name: 'Angoori Rasgulla Bowl',
    description: 'Bite-sized baby rasgullas steeped in rose-scented light syrup, perfect for sweetening individual dessert bowls.',
    price: 300,
    category: 'Sweets',
    rating: 4.6,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=600&auto=format&fit=crop&q=80',
    tags: ['Miniatures', 'Kids Favorite'],
    ingredients: ['Cow Milk Chenna', 'Light Purified Sugar Syrup', 'Rose Essence'],
    nutritionalInfo: 'Calories: 175 kcal | Fat: 3.5g | Sugar: 19g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-20',
    name: 'Assorted Baklava Bites',
    description: 'Crunchy pastry layers containing roasted nuts and drenched in aromatic honey-saffron syrup, baked to golden crispiness.',
    price: 650,
    category: 'Sweets',
    rating: 4.9,
    reviewsCount: 120,
    image: 'https://images.unsplash.com/photo-1605197584547-c93ef1a9c5be?w=600&auto=format&fit=crop&q=80',
    tags: ['Turkish Fusion', 'Exotic Crisp'],
    ingredients: ['Phyllo Sheets', 'Turkish Pistachios', 'Honey Saffron Glaze', 'Pure Ghee Butter'],
    nutritionalInfo: 'Calories: 490 kcal | Fat: 27g | Sugar: 25g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-21',
    name: 'Anjeer Dry Fruit King Roll',
    description: 'An premium sweet crafted with fine Afghan figs, crushed walnuts, cashews, and almonds, free of any refined cane sugar.',
    price: 599,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 75,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Sugar-Free', 'Healthy Choice'],
    ingredients: ['Afghan Figs (Anjeer)', 'Cashew powder', 'Almonds', 'Walnuts', 'Organic Honey touch'],
    nutritionalInfo: 'Calories: 310 kcal | Fat: 14g | Sugar: 0g (Natural Sugars Only)',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-22',
    name: 'Mawa Malai Peda Special',
    description: 'Traditional Mathura-style dark peda cooked intensely with caramelized milk solids and coated in fine sugar dust.',
    price: 320,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    tags: ['Mathura Special', 'Rich Caramel'],
    ingredients: ['Caramelized Khoya', 'Desi Ghee', 'Cardamom', 'Caster Sugar'],
    nutritionalInfo: 'Calories: 430 kcal | Fat: 18g | Sugar: 30g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-23',
    name: 'Saffron Sandesh Sensation',
    description: 'Famous Bengali festive sandesh prepared with freshly curdled chenna, kneaded with sugar and rich Kashmiri saffron strands.',
    price: 360,
    category: 'Sweets',
    rating: 4.7,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Bengali Sweet', 'Soft Texture'],
    ingredients: ['Cow Milk Chenna', 'Sugar', 'Kashmiri Saffron strands', 'Pistachios'],
    nutritionalInfo: 'Calories: 260 kcal | Fat: 9g | Sugar: 21g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-24',
    name: 'Traditional Malai Rabri Pot',
    description: 'Layers of creamy milk fat slow cooked in a clay pot with sugar and green cardamom, serving the finest authentic Indian rabri.',
    price: 380,
    category: 'Sweets',
    rating: 5.0,
    reviewsCount: 183,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Creamy', 'Claypot Special'],
    ingredients: ['A2 Milk cream layers', 'Aromatic Cardamom', 'Sugar', 'Pistachio slivers'],
    nutritionalInfo: 'Calories: 320 kcal | Fat: 16g | Sugar: 24g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-25',
    name: 'Saffron Raj Bhog',
    description: 'Royal enlarged spongy rasgullas filled internally with pistachio, almond, and saffron cardamoms, soaked in warm saffron water.',
    price: 350,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 119,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=600&auto=format&fit=crop&q=80',
    tags: ['Festive', 'Spongy Large'],
    ingredients: ['Chenna dough', 'Kesar infusion', 'Almond bits', 'Sugar syrup'],
    nutritionalInfo: 'Calories: 210 kcal | Fat: 5g | Sugar: 24g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-26',
    name: 'Ghee Coconut Ladoo',
    description: 'Delicious round ladoos made of grated fresh coconut cook in sugar syrup and premium ghee, finished with cardamom.',
    price: 300,
    category: 'Sweets',
    rating: 4.7,
    reviewsCount: 104,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Coconut Special', 'Soft'],
    ingredients: ['Freshly grated Coconut', 'Desi Ghee', 'Cardamom', 'Condensed Milk'],
    nutritionalInfo: 'Calories: 390 kcal | Fat: 19g | Sugar: 32g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-27',
    name: 'Sovereign Kaju Pista Roll',
    description: 'Dual layer sweet containing a outer casing of cashew paste rolled beautifully around a sweet inner Iranian pistachio center.',
    price: 480,
    category: 'Sweets',
    rating: 4.9,
    reviewsCount: 139,
    image: 'https://images.unsplash.com/photo-1605197584547-c93ef1a9c5be?w=600&auto=format&fit=crop&q=80',
    tags: ['Nutty Sensation', 'Bestseller'],
    ingredients: ['Grade W180 Cashews', 'Pistachios', 'Silver leaf vark', 'Organic Sugar'],
    nutritionalInfo: 'Calories: 450 kcal | Fat: 22g | Sugar: 28g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-28',
    name: 'Authentic Agra Petha Kesar',
    description: 'Translucent soft candy made of ash gourd, slow boiled in sugar syrup and heavily infused with rich saffron.',
    price: 280,
    category: 'Sweets',
    rating: 4.6,
    reviewsCount: 65,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    tags: ['Heritage Sweet', 'Saffron Coat'],
    ingredients: ['Ash Gourd (Petha)', 'Saffron water syrup', 'Edible Lime touch'],
    nutritionalInfo: 'Calories: 290 kcal | Fat: 0.1g | Sugar: 55g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-29',
    name: 'Chandrakala Sweet Dumplings',
    description: 'Half-moon crispy pastries stuffed with rich khoya, coconut shreds, and almonds, fried in ghee and dipped in cardamom syrup.',
    price: 360,
    category: 'Sweets',
    rating: 4.8,
    reviewsCount: 82,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Crispy Crust', 'Filled Sweet'],
    ingredients: ['Refined Wheat Flour', 'Rich Khoya filling', 'Shredded Almonds', 'Ghee Fry'],
    nutritionalInfo: 'Calories: 450 kcal | Fat: 21g | Sugar: 33g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },
  {
    id: 'sweet-30',
    name: 'Shahi Khoya Dry Fruit Katori',
    description: 'Cup-shaped premium mawa sweets filled with toasted, caramelized almonds, cashews, and pistachios topped with saffron honey.',
    price: 499,
    category: 'Sweets',
    rating: 5.0,
    reviewsCount: 77,
    image: 'https://images.unsplash.com/photo-1605197584547-c93ef1a9c5be?w=600&auto=format&fit=crop&q=80',
    tags: ['Artisanal Specialty', 'Rich Luxury'],
    ingredients: ['Condensed Milk Mawa', 'Caramelized Cashews', 'Caramelized Almonds', 'Honey Glaze'],
    nutritionalInfo: 'Calories: 470 kcal | Fat: 23g | Sugar: 27g per 100g',
    sizes: ['250g', '500g', '1kg'],
    customizable: false
  },

  // ==================== GIFT BOXES (56 - 75) ====================
  {
    id: 'box-1',
    name: 'Shahi Imperial Assortment Box',
    description: 'A velvet-lined premium gold box featuring our finest collection of Gold-Foil Kaju Katli, Saffron pedas, Royal Dry Fruit Barfi, and Pistachio Baklavas.',
    price: 1800,
    category: 'Gift Boxes',
    rating: 5.0,
    reviewsCount: 198,
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca0a7a02?w=600&auto=format&fit=crop&q=80',
    tags: ['Premium Packaging', 'Gift Perfect', 'Best for Festivals'],
    ingredients: ['Assorted sweets', 'Nut Selection', 'Gold presentation case'],
    sizes: ['Medium Box', 'Grand Box'],
    customizable: false
  },
  {
    id: 'box-2',
    name: 'Golden Celebration Sweets Platter',
    description: 'Celebrate in absolute style with our stunning brass-finish platter loaded with Mysore pak, motichoor laddus, badam halwa tubs, and premium mixed nuts.',
    price: 2500,
    category: 'Gift Boxes',
    rating: 4.9,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['Premium Packaging', 'Luxury Gifting'],
    ingredients: ['Luxury Sweets assortments', 'Cashews, Almonds & Raisins', 'Brass Platter Included'],
    sizes: ['Grand Platter'],
    customizable: false
  },
  {
    id: 'box-3',
    name: 'Velvet Delights Chocolate Hamper',
    description: 'A sumptuous selection of our hand-crafted luxury pralines, Belgian chocolate truffles, hazelnut dragées, and gold dusted premium chocolate bars.',
    price: 1550,
    category: 'Gift Boxes',
    rating: 4.8,
    reviewsCount: 85,
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80',
    tags: ['Chocolate Lover', 'Silk Bow Tie'],
    ingredients: ['Single Origin Cocoa 74%', 'Praline Ganache', 'Premium Roasted Hazelnuts'],
    sizes: ['Regular Bow-Tie', 'VIP Velvet Suite'],
    customizable: false
  },
  {
    id: 'box-4',
    name: 'Royal Silver Sweets Collection',
    description: 'A stellar silver foil themed box featuring Kaju Katli, Silver pedas, coconut burfis, and cardamoms, elegantly handpicked.',
    price: 1350,
    category: 'Gift Boxes',
    rating: 4.7,
    reviewsCount: 62,
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca0a7a02?w=600&auto=format&fit=crop&q=80',
    tags: ['Silver Classic', 'Elegance Pack'],
    ingredients: ['Kaju Katli', 'Coconut Burfi', 'Silver Peda', 'Premium cardboard drawer'],
    sizes: ['Regular Pack'],
    customizable: false
  },
  {
    id: 'box-5',
    name: 'Emerald Pistachio Assortment Box',
    description: 'A stunning emerald green velvet gift box loaded with Pistachio rolls, baklavas, salted pista nuts, and premium green cardamoms.',
    price: 1990,
    category: 'Gift Boxes',
    rating: 4.9,
    reviewsCount: 78,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['Emerald Green', 'Nutty Delight'],
    ingredients: ['Pistachio Sweets', 'Salted Pistachios', 'Velvet gift carrier'],
    sizes: ['Royal Standard'],
    customizable: false
  },
  {
    id: 'box-6',
    name: 'Diamond Jubilee Gifting Suite',
    description: 'Our most grand double-decker gift box containing assorted dry fruit barfis, saffron pedas, badam halwas, and high-grade nuts.',
    price: 3200,
    category: 'Gift Boxes',
    rating: 5.0,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca0a7a02?w=600&auto=format&fit=crop&q=80',
    tags: ['Grand Double-Decker', 'VIP Choice'],
    ingredients: ['Full range sweets', 'Dry Fruit Barfis', 'Luxury brass-finish drawers'],
    sizes: ['Grand Double Suite'],
    customizable: false
  },
  {
    id: 'box-7',
    name: 'Saffron Crested Signature Case',
    description: 'An elegant saffron-colored rigid box packed with saffron gulab jamuns, kesar kalakand, saffron rasgullas, and badam halwa tubs.',
    price: 1650,
    category: 'Gift Boxes',
    rating: 4.8,
    reviewsCount: 55,
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80',
    tags: ['Saffron Theme', 'Signature Box'],
    ingredients: ['Kesar sweets', 'Gulab Jamuns', 'Beautiful presentation tray'],
    sizes: ['Sovereign Pack'],
    customizable: false
  },
  {
    id: 'box-8',
    name: 'Regency Dry Fruit & Sweet Trunk',
    description: 'A genuine wooden chest lined with brass fittings, packed with luxury figs, almonds, cashews, raisins, and dried cherries.',
    price: 2999,
    category: 'Gift Boxes',
    rating: 4.9,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['Wooden Trunk', 'Reusable Gift'],
    ingredients: ['Nuts Assortment', 'Dried Berries', 'Heritage Keepsake Chest'],
    sizes: ['VIP Regency Chest'],
    customizable: false
  },
  {
    id: 'box-9',
    name: 'Classic Celebrations Mithai Box',
    description: 'Our staple festive cardboard box packed with motichoor laddus, kaju katlis, besan laddus, and soan papdi.',
    price: 999,
    category: 'Gift Boxes',
    rating: 4.7,
    reviewsCount: 124,
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca0a7a02?w=600&auto=format&fit=crop&q=80',
    tags: ['Classic Box', 'Budget Friendly'],
    ingredients: ['Assorted Mithais', 'Eco packaging'],
    sizes: ['1 kg Standard Box'],
    customizable: false
  },
  {
    id: 'box-10',
    name: 'Sapphire Luxury Sweet Assortment',
    description: 'A modern navy and gold rigid box loaded with an premium assortment of chocolate-dipped sweets, almond fudge, and kaju rolls.',
    price: 1750,
    category: 'Gift Boxes',
    rating: 4.8,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80',
    tags: ['Sapphire Theme', 'Modern Look'],
    ingredients: ['Chocolate Sweets', 'Almond Fudge', 'Sapphire presentation slide'],
    sizes: ['Medium Sapphire'],
    customizable: false
  },
  {
    id: 'box-11',
    name: 'Ruby Rosewood Gifting Cabinet',
    description: 'A handcrafted rosewood finish cabinet housing twelve drawers of assorted hand-pressed sweets and premium trail mixes.',
    price: 3999,
    category: 'Gift Boxes',
    rating: 5.0,
    reviewsCount: 31,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['Rosewood Cabinet', 'Ultra Luxury'],
    ingredients: ['Select royal sweets', 'Gilded dry fruits', 'Reusable rosewood cabinet'],
    sizes: ['Grand 12-Drawer Cabinet'],
    customizable: false
  },
  {
    id: 'box-12',
    name: 'Sweet Symphony Praline Hamper',
    description: 'An elegant wire-basket hamper filled with hand-rolled chocolates, hazelnut bites, almond biscotti packs, and custom cookies.',
    price: 1450,
    category: 'Gift Boxes',
    rating: 4.6,
    reviewsCount: 34,
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80',
    tags: ['Basket Hamper', 'Bakery mix'],
    ingredients: ['Artisanal Pralines', 'Cookies', 'Almond Biscotti', 'Tasselled Basket'],
    sizes: ['Harmony Basket'],
    customizable: false
  },
  {
    id: 'box-13',
    name: 'Majestic Brass Thali Platter',
    description: 'A massive hand-carved solid brass platter piled with golden modaks, premium pedas, ghee laddus, and cashew nuts.',
    price: 2800,
    category: 'Gift Boxes',
    rating: 4.9,
    reviewsCount: 67,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['Brass Keepsake', 'Festive Glory'],
    ingredients: ['Laddus', 'Modaks', 'Dry fruits', 'Carved Solid Brass Platter'],
    sizes: ['Imperial Platter'],
    customizable: false
  },
  {
    id: 'box-14',
    name: 'Heritage Tin Keepsake Box',
    description: 'Beautiful vintage-themed embossed metal tin filled with crispy soan papdi, motichoor laddus, and salted cashews.',
    price: 1100,
    category: 'Gift Boxes',
    rating: 4.7,
    reviewsCount: 59,
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca0a7a02?w=600&auto=format&fit=crop&q=80',
    tags: ['Tin Box', 'Vintage Style'],
    ingredients: ['Soan Papdi', 'Motichoor Laddu', 'Salted Cashew nuts'],
    sizes: ['Heritage Standard'],
    customizable: false
  },
  {
    id: 'box-15',
    name: 'Pure Ghee Sweets Tri-Pack',
    description: 'Three micro boxes tied with a silk ribbon, featuring Mysore pak, malai peda, and besan laddu.',
    price: 850,
    category: 'Gift Boxes',
    rating: 4.8,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80',
    tags: ['Tri-Pack', 'Mini Gifting'],
    ingredients: ['Mysore Pak', 'Besan Laddu', 'Milk Peda'],
    sizes: ['Tri-Pack regular'],
    customizable: false
  },
  {
    id: 'box-16',
    name: 'Elite Executive Gift Tray',
    description: 'A sleek leather-ette dark tray loaded with premium pistachio baklavas, sugar-free date barfis, and raw forest honey jar.',
    price: 2200,
    category: 'Gift Boxes',
    rating: 4.9,
    reviewsCount: 45,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['Leather Tray', 'Corporate Perfect'],
    ingredients: ['Baklavas', 'Date Barfi', 'Forest Honey', 'Sleek dark tray'],
    sizes: ['Executive Size'],
    customizable: false
  },
  {
    id: 'box-17',
    name: 'Kids Joy Festive Sweet Box',
    description: 'A colorful animated box containing rainbow cakes, chocolate cupcakes, kaju katli starlets, and delicious sugar-free milk candies.',
    price: 750,
    category: 'Gift Boxes',
    rating: 4.7,
    reviewsCount: 91,
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca0a7a02?w=600&auto=format&fit=crop&q=80',
    tags: ['Kids Pack', 'Fun Design'],
    ingredients: ['Cupcakes', 'Mini Cakes', 'Mild Sweets'],
    sizes: ['Standard Joy Box'],
    customizable: false
  },
  {
    id: 'box-18',
    name: 'Golden Glow Diwali Trunk',
    description: 'A gold embossed tin treasure trunk filled with Kashmiri saffron, dry figs, walnuts, gold-dusted pedas, and aromatic candles.',
    price: 2600,
    category: 'Gift Boxes',
    rating: 5.0,
    reviewsCount: 83,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['Diwali Special', 'Treasure Trunk'],
    ingredients: ['Saffron', 'Walnuts', 'Figs', 'Golden pedas', 'Scented candles'],
    sizes: ['VIP Diwali Chest'],
    customizable: false
  },
  {
    id: 'box-19',
    name: 'Royal Satin Bow Pista Case',
    description: 'An elegant square slide-out box with a heavy gold satin bow, featuring purely pistachio rolls and salted pistachios.',
    price: 1500,
    category: 'Gift Boxes',
    rating: 4.8,
    reviewsCount: 39,
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?w=600&auto=format&fit=crop&q=80',
    tags: ['Satin Bow', 'Pista Lovers'],
    ingredients: ['Pistachio Sweets', 'Salted Pista', 'Luxury presentation case'],
    sizes: ['Standard Satin Box'],
    customizable: false
  },
  {
    id: 'box-20',
    name: 'Grand Sovereignty Sweet Chest',
    description: 'Our ultimate luxury cabinet chest containing 24 assortments of milk pedas, kaju sweets, chocolate truffles, baklavas, and nuts.',
    price: 4500,
    category: 'Gift Boxes',
    rating: 5.0,
    reviewsCount: 22,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['Ultimate Luxury', 'Masterpieces Case'],
    ingredients: ['All signature sweets', 'Exotic trial mix', 'Massive reusable drawer chest'],
    sizes: ['VIP Imperial Chest'],
    customizable: false
  },

  // ==================== BAKERY ITEMS (76 - 90) ====================
  {
    id: 'bakery-1',
    name: 'Flaky Butter Croissants',
    description: 'French style classic butter croissants with hundreds of hand-folded flaky layers, baked till golden brown and incredibly crisp.',
    price: 180,
    category: 'Bakery Items',
    rating: 4.8,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    tags: ['Freshly Baked', 'Breakfast Classic'],
    ingredients: ['French Charentes Butter', 'Organic Flour', 'Yeast', 'Sea Salt'],
    sizes: ['2 Pcs Pack', '4 Pcs Pack'],
    customizable: false
  },
  {
    id: 'bakery-2',
    name: 'Pain au Chocolat',
    description: 'Rich yeast leavened puff pastry wrapped around rods of dark semi-sweet Belgian chocolate, baked fresh daily.',
    price: 199,
    category: 'Bakery Items',
    rating: 4.8,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600&auto=format&fit=crop&q=80',
    tags: ['Chocolate Puff', 'French Special'],
    ingredients: ['French Butter', 'Belgian Chocolate rod', 'Wheat Flour', 'Vanilla extract'],
    sizes: ['2 Pcs Pack'],
    customizable: false
  },
  {
    id: 'bakery-3',
    name: 'Premium Almond Croissant',
    description: 'Double-baked croissant filled with rich sweet almond frangipane cream, topped with toasted sliced almonds and powdered sugar.',
    price: 240,
    category: 'Bakery Items',
    rating: 4.9,
    reviewsCount: 83,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    tags: ['Nutty Croissant', 'Chef\'s Special'],
    ingredients: ['Almond frangipane', 'Flaky Croissant dough', 'Slivered almonds', 'Sugar dusting'],
    sizes: ['1 Pc Regular'],
    customizable: false
  },
  {
    id: 'bakery-4',
    name: 'Double Chocolate Fudge Brownies',
    description: 'Rich, dense, fudgy chocolate brownies containing generous chunks of Belgian milk chocolate and finished with cocoa dusting.',
    price: 220,
    category: 'Bakery Items',
    rating: 4.9,
    reviewsCount: 151,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    tags: ['Super Fudgy', 'Chocolate Feast'],
    ingredients: ['70% Cocoa butter', 'Belgian Chocolate chips', 'Amul Butter', 'Brown sugar'],
    sizes: ['2 Brownie Slices', 'Box of 6 Slices'],
    customizable: false
  },
  {
    id: 'bakery-5',
    name: 'Red Velvet Cream Cheese Cookies',
    description: 'Beautiful bright crimson cookies with soft chewy centers, holding a rich white cream cheese chocolate center.',
    price: 180,
    category: 'Bakery Items',
    rating: 4.7,
    reviewsCount: 66,
    image: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=600&auto=format&fit=crop&q=80',
    tags: ['Chewy Cookie', 'Creamy Heart'],
    ingredients: ['Red Velvet Batter', 'Cream Cheese Chunks', 'Vanilla sugar'],
    sizes: ['Pack of 4 Cookies'],
    customizable: false
  },
  {
    id: 'bakery-6',
    name: 'Classic Choc-Chip Giant Cookie',
    description: 'Freshly baked giant chocolate chip cookie holding soft doughy centers and crisp outer margins, overloaded with dark choc chips.',
    price: 150,
    category: 'Bakery Items',
    rating: 4.8,
    reviewsCount: 119,
    image: 'https://images.unsplash.com/photo-1558961309-dbdf056fb4ce78?w=600&auto=format&fit=crop&q=80',
    tags: ['Giant Cookie', 'All-Time Classic'],
    ingredients: ['Dark Chocolate chips', 'Molasses Sugar', 'Salted Butter', 'Organic flour'],
    sizes: ['1 Giant Cookie'],
    customizable: false
  },
  {
    id: 'bakery-7',
    name: 'Wild Blueberry Streusel Muffins',
    description: 'Moist golden muffins filled with wild blueberries and topped with a crunchy buttery sugar streusel topping.',
    price: 160,
    category: 'Bakery Items',
    rating: 4.6,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop&q=80',
    tags: ['Berry Muffin', 'Crunchy Top'],
    ingredients: ['Wild Blueberries', 'Buttermilk', 'Butter Streusel crumble', 'Vanilla bean extract'],
    sizes: ['Pack of 2 Muffins'],
    customizable: false
  },
  {
    id: 'bakery-8',
    name: 'Rich English Fruit Cake Loaf',
    description: 'A traditional rich butter sponge cake packed with spiced raisins, dried cherries, orange peels, and walnuts.',
    price: 399,
    category: 'Bakery Items',
    rating: 4.7,
    reviewsCount: 71,
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=600&auto=format&fit=crop&q=80',
    tags: ['Spiced Cake', 'Tea Time Classic'],
    ingredients: ['Sultanas', 'Dried Cherries', 'Orange Zest', 'Rich Butter sponge', 'Rum Essence flavor'],
    sizes: ['400g Loaf'],
    customizable: false
  },
  {
    id: 'bakery-9',
    name: 'Garlic Butter Artisan Baguette',
    description: 'Crispy and crusty French style long baguette sliced and stuffed with rich garlic-herb butter, ready to toast.',
    price: 150,
    category: 'Bakery Items',
    rating: 4.8,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    tags: ['Herbed', 'Ready-to-Bake'],
    ingredients: ['French Baguette dough', 'Garlic paste', 'Fresh Parsley', 'Salted Butter'],
    sizes: ['1 Long Sliced Baguette'],
    customizable: false
  },
  {
    id: 'bakery-10',
    name: 'Artisan Sourdough Loaf',
    description: 'Handcrafted wild-fermented sourdough bread loaf with a thick bubbly crust and soft sour interior pockets.',
    price: 220,
    category: 'Bakery Items',
    rating: 4.9,
    reviewsCount: 104,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    tags: ['Sourdough', 'Healthy Artisan'],
    ingredients: ['Wild Sourdough Starter', 'Unbleached Wheat Flour', 'Purified Water', 'Himalayan Salt'],
    sizes: ['500g Sourdough Boule'],
    customizable: false
  },
  {
    id: 'bakery-11',
    name: 'French Macaron Assortment Pack',
    description: 'A colorful pack of classic delicate French almond meringue macarons filled with strawberry, chocolate, lemon, and pistachio ganache.',
    price: 450,
    category: 'Bakery Items',
    rating: 4.9,
    reviewsCount: 132,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
    tags: ['Macarons Pack', 'Premium Delight'],
    ingredients: ['Almond meal', 'Egg white meringue', 'Chocolate ganache', 'Citrus curd'],
    sizes: ['Box of 6 Macarons', 'Box of 12 Macarons'],
    customizable: false
  },
  {
    id: 'bakery-12',
    name: 'Italian Almond Biscotti',
    description: 'Double baked crispy biscotti containing whole roasted almonds, flavored with anise and sweet orange zest, ideal for dipping in coffee.',
    price: 250,
    category: 'Bakery Items',
    rating: 4.7,
    reviewsCount: 48,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    tags: ['Crispy Biscuit', 'Coffee Match'],
    ingredients: ['Roasted Almonds', 'Flour', 'Sugar', 'Anise seeds', 'Orange peel extract'],
    sizes: ['150g Bottle'],
    customizable: false
  },
  {
    id: 'bakery-13',
    name: 'Red Velvet Molten Lava Cookie',
    description: 'A deep red velvet cookie stuffed with rich white chocolate lava which oozes out when warmed.',
    price: 180,
    category: 'Bakery Items',
    rating: 4.8,
    reviewsCount: 57,
    image: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=600&auto=format&fit=crop&q=80',
    tags: ['Molten Core', 'Super Chewy'],
    ingredients: ['Red Velvet Cocoa Base', 'White Chocolate Core', 'Brown Sugar'],
    sizes: ['2 Lava Cookies Pack'],
    customizable: false
  },
  {
    id: 'bakery-14',
    name: 'Dark Chocolate Sea Salt Sables',
    description: 'Buttery French shortbread cookies baked with Belgian dark cocoa and finished with a dusting of fleur de sel sea salt.',
    price: 210,
    category: 'Bakery Items',
    rating: 4.9,
    reviewsCount: 65,
    image: 'https://images.unsplash.com/photo-1558961309-dbdf056fb4ce78?w=600&auto=format&fit=crop&q=80',
    tags: ['Salted Choc', 'Buttery Crisp'],
    ingredients: ['French Butter', 'Valrhona Cocoa powder', 'Fleur de Sel', 'Powdered sugar'],
    sizes: ['200g Tin'],
    customizable: false
  },
  {
    id: 'bakery-15',
    name: 'Saffron Pistachio Shortbread',
    description: 'Classic Scottish style shortbread containing a royal fusion of ground Kashmiri saffron and roasted Persian pistachio chunks.',
    price: 280,
    category: 'Bakery Items',
    rating: 4.9,
    reviewsCount: 72,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    tags: ['Fusion Biscuit', 'Premium Butter'],
    ingredients: ['Grass-fed butter', 'Kashmiri Saffron', 'Slivered Pistachios', 'Wheat flour'],
    sizes: ['200g Gift Tin'],
    customizable: false
  },

  // ==================== FESTIVAL SPECIALS (91 - 105) ====================
  {
    id: 'fest-1',
    name: 'Diwali Shahi Premium Thali',
    description: 'A royal brass thali packed with custom hand-pressed modaks, kesar jalebi loops, rich dry fruit kaju rolls, silver-lined pedas, and positive energy.',
    price: 1999,
    category: 'Festival Specials',
    rating: 5.0,
    reviewsCount: 245,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    tags: ['Festival Limited', 'Royalty Pack'],
    ingredients: ['Kaju Rolls', 'Motichoor Laddus', 'Kesar Peda', 'Kaju Katli', 'Brass Thali'],
    sizes: ['Imperial Family Pack'],
    customizable: false
  },
  {
    id: 'fest-2',
    name: 'Ganesha Gold Modak Box',
    description: 'Handcrafted traditional steamed and fried modaks with an aromatic filling of fresh grated coconut, liquid gold jaggery, and premium cardamoms.',
    price: 499,
    category: 'Festival Specials',
    rating: 4.9,
    reviewsCount: 165,
    image: 'https://images.unsplash.com/photo-1605197584547-c93ef1a9c5be?w=600&auto=format&fit=crop&q=80',
    tags: ['Ganesh Chaturthi Limited', 'Divine Sweet'],
    ingredients: ['Steamed Rice Flour', 'Aromatic Jaggery', 'Fresh Grated Coconut', 'Pure Saffron Ghee'],
    sizes: ['11 Pieces Box', '21 Pieces Feast Box'],
    customizable: false
  },
  {
    id: 'fest-3',
    name: 'Holi Premium Gujiya Platter',
    description: 'Golden deep-fried pastries shaped beautifully and filled with sweetened khoya, roasted almonds, cashews, and aromatic cardamom, dipped in saffron syrup.',
    price: 599,
    category: 'Festival Specials',
    rating: 4.8,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Holi Festival', 'Crispy Filled'],
    ingredients: ['Refined Flour wrapper', 'Sweetened Mawa filling', 'Cardamom', 'Cashews & Almonds'],
    sizes: ['12 Pcs Platter Box'],
    customizable: false
  },
  {
    id: 'fest-4',
    name: 'Rakhi Kesar Mithai Hamper',
    description: 'An premium hamper with a designer Rakhi thread, packed with Saffron pedas, Kaju Katli, and customized premium almonds.',
    price: 899,
    category: 'Festival Specials',
    rating: 4.9,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca0a7a02?w=600&auto=format&fit=crop&q=80',
    tags: ['Raksha Bandhan', 'Silk Bow Case'],
    ingredients: ['Designer Rakhi Thread', 'Saffron Peda', 'Premium Almonds', 'Kaju Katli'],
    sizes: ['Standard Rakhi Box'],
    customizable: false
  },
  {
    id: 'fest-5',
    name: 'Eid Royal Sheer Khurma Mix',
    description: 'Premium gift glass jar loaded with toasted fine vermicelli, dates, saffron, green cardamoms, pistachios, almonds, and chironji nuts.',
    price: 380,
    category: 'Festival Specials',
    rating: 4.8,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Eid Festival', 'Luxury Mix'],
    ingredients: ['Fine wheat vermicelli', 'Dry Dates (Kharek)', 'Saffron', 'Assorted Sliced Nuts'],
    sizes: ['350g Glass Jar'],
    customizable: false
  },
  {
    id: 'fest-6',
    name: 'Pongal Sweet Ghee Claypot',
    description: 'Traditional earthen pot filled with fragrant freshly cooked sweet jaggery rice, boiled in pure milk, abundant ghee, roasted cashews, and raisins.',
    price: 450,
    category: 'Festival Specials',
    rating: 4.9,
    reviewsCount: 83,
    image: 'https://images.unsplash.com/photo-1621941400262-6cfa733d7b87?w=600&auto=format&fit=crop&q=80',
    tags: ['Sankranti Pongal', 'Traditional Pot'],
    ingredients: ['Fragrant Raw Rice', 'Organic Liquid Jaggery', 'Pure Cow Ghee', 'Cashew nuts', 'Earthen Pot'],
    sizes: ['Standard Claypot'],
    customizable: false
  },
  {
    id: 'fest-7',
    name: 'Durga Puja Sandesh Thali',
    description: 'An auspicious copper thali holding custom handcrafted Shankha-shaped sandesh, malai pedas, and saffron rasgullas.',
    price: 799,
    category: 'Festival Specials',
    rating: 4.9,
    reviewsCount: 121,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    tags: ['Pujo Special', 'Auspicious Pack'],
    ingredients: ['Hand-molded Sandesh', 'Copper Thali Platter', 'Milk Pedas', 'Kesar Rasgullas'],
    sizes: ['Pujo Sovereign Thali'],
    customizable: false
  },
  {
    id: 'fest-8',
    name: 'Janmashtami Sweet Makhan Cup',
    description: 'A miniature ceramic pot filled with sweetened freshly churned organic white butter, flavored with saffron water and crystal sugar.',
    price: 299,
    category: 'Festival Specials',
    rating: 4.9,
    reviewsCount: 78,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Janmashtami Special', 'Divine Makhan'],
    ingredients: ['Freshly Churned Cow Milk Butter', 'Saffron drops', 'Misri (Crystal Sugar)'],
    sizes: ['Ceramic Matki (200g)'],
    customizable: false
  },
  {
    id: 'fest-9',
    name: 'Christmas Spiced Plum Cake',
    description: 'A traditional dark rich plum cake loaded with rum-steeped raisins, black currants, glazed orange skins, almonds, and warm winter spices.',
    price: 650,
    category: 'Festival Specials',
    rating: 5.0,
    reviewsCount: 184,
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=600&auto=format&fit=crop&q=80',
    tags: ['Christmas Special', 'Steeped Fruits'],
    ingredients: ['Soaked Black Currants', 'Glazed Cherries', 'Clove & Nutmeg', 'Brown butter', 'Plum glaze'],
    sizes: ['500g Loaf Box', '1kg Elegant Round Case'],
    customizable: false
  },
  {
    id: 'fest-10',
    name: 'Navratri Vrat Rajgira Peda',
    description: 'Fasting friendly sweet pedas prepared from roasted amaranth flour, reduced cow milk, cardamom, and pure honey.',
    price: 360,
    category: 'Festival Specials',
    rating: 4.7,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    tags: ['Navratri Vrat', 'Fasting Friendly'],
    ingredients: ['Amaranth Flour (Rajgira)', 'Reduced Milk Solids', 'Organic Honey', 'Cardamom'],
    sizes: ['250g Pack', '500g Pack'],
    customizable: false
  },
  {
    id: 'fest-11',
    name: 'Dussehra Victory Jalebi Urn',
    description: 'A huge decorative tin urn containing giant premium saffron jalebis fried in desi ghee, perfect for celebrating Vijayadashami family feasts.',
    price: 499,
    category: 'Festival Specials',
    rating: 4.8,
    reviewsCount: 102,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=600&auto=format&fit=crop&q=80',
    tags: ['Dussehra Classic', 'Huge Jalebis'],
    ingredients: ['Fermented wheat flour batter', 'Pure Cow Ghee', 'Cardamom syrup', 'Auspicious Tin Urn'],
    sizes: ['1 kg Victory Urn'],
    customizable: false
  },
  {
    id: 'fest-12',
    name: 'Makar Sankranti Til Laddu Urn',
    description: 'Crunchy round laddus made of roasted white sesame seeds bound together beautifully in warm liquid organic sugarcane jaggery.',
    price: 320,
    category: 'Festival Specials',
    rating: 4.8,
    reviewsCount: 91,
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80',
    tags: ['Sankranti Til', 'Warm Crunch'],
    ingredients: ['Roasted White Sesame Seeds', 'Organic Sugarcane Jaggery', 'Ghee glaze'],
    sizes: ['400g Glass Pot'],
    customizable: false
  },
  {
    id: 'fest-13',
    name: 'Karwa Chauth Sargi Hamper',
    description: 'A custom fast-opening box holding sweet vermicelli kheer mix, fresh premium mathris, almonds, and saffron pedas.',
    price: 699,
    category: 'Festival Specials',
    rating: 4.7,
    reviewsCount: 46,
    image: 'https://images.unsplash.com/photo-1549007994-cb92ca0a7a02?w=600&auto=format&fit=crop&q=80',
    tags: ['Karwa Chauth', 'Sargi Pack'],
    ingredients: ['Fresh Mathri', 'Sweet vermicelli mix', 'Saffron pedas', 'Serrated almonds'],
    sizes: ['Standard Sargi Box'],
    customizable: false
  },
  {
    id: 'fest-14',
    name: 'Lohri Premium Gur Til Platter',
    description: 'A grand Lohri celebration tray containing crispy peanut chikki chunks, black sesame gajak slabs, roasted peanuts, and popcorn bags.',
    price: 550,
    category: 'Festival Specials',
    rating: 4.9,
    reviewsCount: 79,
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=600&auto=format&fit=crop&q=80',
    tags: ['Lohri Special', 'Crispy Jaggery'],
    ingredients: ['Roasted Peanuts', 'Organic Gur (Jaggery)', 'Black Sesame', 'Popcorn seeds'],
    sizes: ['Standard Festival Tray'],
    customizable: false
  },
  {
    id: 'fest-15',
    name: 'New Year Premium Cupcake Platter',
    description: 'A beautiful platter of twelve chocolate and red-velvet cupcakes piped with golden buttercream and topped with gold flakes.',
    price: 1199,
    category: 'Festival Specials',
    rating: 4.8,
    reviewsCount: 63,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
    tags: ['New Year Vibe', 'Celebration Cupcakes'],
    ingredients: ['Vanilla & Cocoa Batter', 'Swiss Meringue buttercream', 'Edible Gold foil flakes'],
    sizes: ['Platter of 12 Cupcakes'],
    customizable: false
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'rev-1',
    name: 'Aditya Vardhan',
    role: 'Luxury Connoisseur',
    rating: 5,
    comment: 'The Belgian Chocolate Truffle Cake from SRM Sweets & Cakes is a work of pure culinary art. The 24k gold leaf and deep dark chocolate layers offer an unparalleled luxury taste.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'rev-2',
    name: 'Meera Krishnan',
    role: 'Food Stylist',
    rating: 5,
    comment: 'Their Kaju Katli has the smoothest cashew texture I\'ve ever experienced. Not overly sweet, and the presentation in their velvet boxes makes it my ultimate choice for gifting.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'rev-3',
    name: 'Rohan Singhania',
    role: 'Corporate Director',
    rating: 5,
    comment: 'We ordered 200 Golden Celebration platters for our Diwali corporate event. The feedback from our VIP clients was spectacular. A brand that truly understands premium quality and luxury aesthetics.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80'
  }
];

export const STATS_COUNTERS = [
  { value: '25+', label: 'Artisanal Flavors' },
  { value: '100% ', label: 'Pure A2 Desi Ghee' },
  { value: '50k+', label: 'Delighted Royalty' },
  { value: '4.9 ★', label: 'Customer Rating' }
];

export const FESTIVAL_OFFERS = [
  {
    id: 'offer-1',
    code: 'FESTIVE15',
    title: 'Royal Celebration Discount',
    description: 'Unlock 15% off on our Luxury Gift Boxes & Saffron Specials.',
    discountPercent: 15,
    minAmount: 1500
  },
  {
    id: 'offer-2',
    code: 'SRMROYAL',
    title: 'First Order Privilege',
    description: 'Get a complimentary hand-painted Motichoor Laddu box on orders above ₹1000.',
    discountPercent: 10,
    minAmount: 1000
  }
];
